edificio_administrativo/urls.py
from django.contrib import admin
from django.urls import path, include
from edificio_app import views
from edificio_app.views import *




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', (indexView.as_view()), name='index'),
    path('edificio/visitantes/',(CreateVisitanteFormView.as_view()), name='visitantes'),
    path('edificio/salida/',(VisitantesSalidaView.as_view()), name='salida'),
    path('obtener_datos_visitante/<int:cedula>/', ObtenerDatosVisitanteView.as_view(), name='obtener_datos_visitante'),
    path('salida/<int:visitante_id>/', SalidaView.as_view(), name='salida_visitante'),
    path('edificio/empleados/',(EmpleadoslistView.as_view()), name='empleados'),
    path('edificio/crearEmpleados/', (CreateEmpleadoFormView.as_view()), name='crearEmpleados'),
    path('editar_empleado/<int:empleado_id>/', EditarEmpleadoView.as_view(), name='editarEmpleados'),
    path('eliminar_empleado/<int:empleado_id>/', EliminarEmpleadoView.as_view(), name='eliminar_empleado'),
    path('edificio/reportes/',(ReportesView.as_view()), name='reportes'),
    path('generar_excel/', (GenerarExcelView.as_view()), name='generar_excel'),
    path('edificio/users/',(UsersListView.as_view()), name='users'),
    path('edificio/editarEmpleados/',(EmpleadosEditView.as_view()), name='editarEmpleados'),
    path('edificio/createUsers/',(UsersCreateView.as_view()), name='crearUsers'),
    path('editar_usuario/<int:usuario_id>/', (EditarUsuarioView.as_view()), name='editarUsuarios'),
    path('eliminar_usuario/<int:usuario_id>/', (EliminarUsuarioView.as_view()), name='eliminar_usuario'),
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cedula/',views.completarCedula)

]

edificio_app/models.py
from django.db import models
from .choices import options_Equipos
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager, PermissionsMixin


class UsuarioManager(BaseUserManager):
    def _create_user(self,username,email,nombres,password,is_staff,is_superuser,**extra_fields):
        user = self.model(
            username = username,
            email = email,
            nombres = nombres,
            is_staff = is_staff,
            is_superuser = is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self.db)
        return user
    
    def create_user(self,username,email,nombres,password = None,**extra_fields):
        return self._create_user(username,email,nombres,password,False,False,**extra_fields)
    
    def create_superuser(self,username,email,nombres,password = None,**extra_fields):
        return self._create_user(username,email,nombres,password,True,True,**extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('Nombre de Usuario',unique=True,max_length=100)
    email = models.EmailField('Correo Electronico',unique=True,max_length=254)
    nombres = models.CharField('Nombres', blank= True , null=True ,max_length=255)
    apellidos = models.CharField('Apellidos', blank= True , null=True ,max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    objects = UsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','nombres','apellidos']

    def __str__(self):
        return f'Usuario {self.nombres}.{self.apellidos}'

class Visitantes(models.Model):
    identificacion = models.IntegerField()
    nombres = models.CharField(max_length=255)
    apellidos = models.CharField(max_length=255)
    celular = models.IntegerField()
    empresa = models.CharField(max_length=255)
    area_id = models.ForeignKey('Area', on_delete=models.CASCADE)
    empleado_id = models.ForeignKey('Empleado', on_delete=models.CASCADE)
    tipo_equipo = models.CharField(max_length=25, choices=options_Equipos, blank=True, null=True)
    marca = models.CharField(max_length=255, blank=True, null=True)
    serial = models.CharField(max_length=255,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso')

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"

class Area(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255, default='')
    area = models.ForeignKey(Area, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class Salida(models.Model):
    visitante = models.OneToOneField('Visitantes', on_delete=models.CASCADE)
    fecha_salida = models.DateTimeField(auto_now_add=True, verbose_name='Fecha Salida')

edificio_app/forms.py
from django import forms
from .models import Area, Empleado, Visitantes , Usuario , options_Equipos
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group

class RegistroVisitanteForm(forms.ModelForm):
    
    identificacion = forms.IntegerField(label='Cedula',required=True,widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca la cedula'}))
    nombres = forms.CharField(label='Nombre', required=True,max_length=25,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Introduzca el nombre'}))
    apellidos = forms.CharField(label='Apellido', required=True,max_length=25,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Introduzca el apellido'}))
    celular = forms.IntegerField(label='Celular',required=True,widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca la celular'}))
    empresa = forms.CharField(label='Empresa', required=True,max_length=25,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Introduzca la empresa'}))
    area_id = forms.ModelChoiceField(queryset=Area.objects.all(),label='Área de Visita',required=True,empty_label="Seleccione un área",
    widget=forms.Select(attrs={'class': 'form-control'}))
    empleado_id = forms.ModelChoiceField(queryset=Empleado.objects.all(),label='Empleado',required=True,empty_label="Seleccione un Empleado",
    widget=forms.Select(attrs={'class': 'form-control'}))
    tipo_equipo = forms.ChoiceField(label='Equipo',choices=options_Equipos,required=False,widget=forms.Select(attrs={'class': 'form-control'}))
    marca = forms.CharField(label='Marca',required=False,max_length=10,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca la marca'}))
    serial = forms.CharField(label='serial',required=False,max_length=20,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Introduzca el serial'}))

    class Meta:
        model = Visitantes
        fields = ['identificacion', 'nombres', 'apellidos', 'celular', 'empresa', 'area_id', 'empleado_id', 'tipo_equipo', 'marca', 'serial']

class EmpleadoForm(forms.ModelForm):
    nombre = forms.CharField(label='Nombre', required=True,max_length=25,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Introduzca el nombre'}))
    apellido = forms.CharField(label='Apellido', required=True,max_length=25,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Introduzca el apellido'}))
    area = forms.ModelChoiceField(queryset=Area.objects.all(),label='Área de Visita',required=True,empty_label="Seleccione un área",
    widget=forms.Select(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Empleado
        fields = [ 'nombre', 'apellido', 'area']

class UsuarioForm(forms.ModelForm): 
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Ingrese su contraseña...','required':'required'}))
    password2 = forms.CharField(label='Contraseña De Confirmación', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Ingrese nuevamente su contraseña...','required':'required'}))

    # Campo adicional para elegir el tipo de usuario
    tipo_usuario = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Tipo de Usuario'
    )

    class Meta:
        model = Usuario  
        fields = ['email', 'username', 'nombres', 'apellidos','tipo_usuario']  
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
            'nombres': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su Nombre'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su Apellido'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su usuario'}),
        }

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body style="overflow-x: hidden;">
  <img id="apostar" src="{% static 'img/apostar1.jpg' %}" style="width: 100%;">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 4px;">
          <img alt="Brand" src="{% static 'img/apostar.jpg' %}" style="width: 40px; height: 40px;">
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'login' %}">Salir</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

</body>
</html>

templates/crearVisitante.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- <title> {{ titulo }} </title> -->
  <title>VISITANTES</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/crearVisitante.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <img id="apostar" src="{% static 'img/apostar1.jpg' %}" style="width: 100%;height: 106px;">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 4px;">
          <img alt="Brand" src="{% static 'img/apostar.jpg' %}" style="width: 40px; height: 40px;">
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}">menú</a></li>
          <li><a href="{% url 'login' %}">Salir</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <center style="width: 100%;">
    <div class="" >
      <div class="page-title">
      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h3>Ingresar visitante <h6></h6></h3>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
            <form method="POST" action="" accept-charset="UTF-8" autocomplete="off"
                class="form-horizontal form-label-left" id="visitante" enctype="multipart/form-data">
                  {% csrf_token %}
                  
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="Cédula : " class="control-label col-md-3 col-sm-3 col-xs-12"
                      for="identificacion">C&eacute;dula : </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="identificacion" class="form-control col-md-7 col-xs-12" placeholder="Ingrese la cedula"
                        name="identificacion" type="number" required>
                      <span class="input-group-btn">
                      </span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Nombres : " class="control-label col-md-3 col-sm-3 col-xs-12" for="nombres">Nombres :
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="nombres" class="form-control col-md-7 col-xs-12" placeholder="Ingrese el nombre"
                        name="nombres" type="text" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Apellidos : " class="control-label col-md-3 col-sm-3 col-xs-12"
                      for="apellidos">Apellidos : </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="apellidos" class="form-control col-md-7 col-xs-12" placeholder="Ingrese el apellido"
                        name="apellidos" type="text" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Celular : " class="control-label col-md-3 col-sm-3 col-xs-12" for="celular">Celular :
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="celular" class="form-control col-md-7 col-xs-12" placeholder="Ingrese el celular"
                        name="celular" type="number" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Empresa : " class="control-label col-md-3 col-sm-3 col-xs-12" for="empresa">Empresa :
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input id="empresa" class="form-control col-md-7 col-xs-12" placeholder="Ingrese la empresa"
                        name="empresa" type="text" required>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Area de visita : " class="control-label col-md-3 col-sm-12 col-xs-12" for="role_id">Area De Visita : </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select id="area_id" class="form-control col-md-7 col-xs-12 btn btn-default" name="area_id" required>
                            <option selected="selected" value="">Seleccione El area</option>
                            {% for area in form.area_id.field.queryset %}
                                <option value="{{ area.id }}" data-area-id="{{ area.id }}">{{ area.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                                
                <div class="form-group">
                  <label for="Empleado : " class="control-label col-md-3 col-sm-12 col-xs-12" for="role_id">Empleado : </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <select id="id_empleado_id" class="form-control col-md-7 col-xs-12 btn btn-default" name="empleado_id" required>
                          <option selected="selected" value="">Seleccione el empleado</option>
                          {% for empleado in form.empleado_id.field.queryset %}
                              <option value="{{ empleado.id }}" data-area-id="{{ empleado.area_id }}">{{ empleado.nombre }}</option>
                          {% endfor %}
                      </select>
                  </div>
              </div>                    
                  <div class="form-group">
                    <label for="Ingresar equipo : " class="control-label col-md-3 col-sm-12 col-xs-12"
                      for="role_id">Ingresar Equipo : </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <button type="button" class="btn btn-primary" id="equipo" data-toggle="modal" data-target="#myModal">Ingresar</button>
                        <button type="reset" class="btn btn-primary" id="btnBorrar">Limpiar</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-6" id="my_camera" style="width:320px; height:240px;"></div>
                    <input id="imagen" type="hidden" name="imagen" value="" />
                    <input id="oldimagen" type="hidden" name="oldimagen" value="" />
                    <div class="col-md-5 col-md-offset-1" id="my_result">
                      <img id="imagenvisitante" src="" />
                    </div>
                  </div>
                  
                  <div class="row">
                  </div>
                </div>
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Equipo</h4>
                      </div>
                      <div class="modal-body">
                          <div class="form-group">
                            <label for="{{ form.tipo_equipo.id_for_label }}" class="control-label col-md-4 col-sm-12 col-xs-12">Tipo De Equipo :</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              {{ form.tipo_equipo }}
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="{{ form.marca.id_for_label }}" class="control-label col-md-4 col-sm-3 col-xs-12">Marca :</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              {{ form.marca }}
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="{{ form.serial.id_for_label }}" class="control-label col-md-4 col-sm-3 col-xs-12">Serial :</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              {{ form.serial }}
                            </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                      <input id="crear" class="btn btn-primary" type="submit" value="Crear">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    <div class="col-md-6" style="float: right; margin-right: 10px; margin-top: 20px;">
        <video id="camera-feed" autoplay></video>
        <button id="capture-button">Capturar Datos</button>
        <canvas id="captured-image" style="display: none; width: 20%;"></canvas>
    </div>     
    <script src="{% static 'js/create.js' %}"></script>
    <script src="{% static 'js/sweetAlert/CrearVisitanteSweetAlert.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  </center>
</body>
</html>

templates/empleados.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title> {{ titulo }} </title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/empleados.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body style="overflow-x: hidden;">
  <img id="apostar" src="{% static 'img/apostar1.jpg' %}" style="width: 100%;">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 4px;">
          <img alt="Brand" src="{% static 'img/apostar.jpg' %}" style="width: 40px; height: 40px;">
        </a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}">menú</a></li>
          <li><a href="{% url 'login' %}">Salir</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h3>Listado de empleados </h3>
          <ul class="nav navbar-right panel_toolbox">
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <a href="{% url 'crearEmpleados' %}" type="button" class="btn btn-danger">Crear empleado</a>
          <table id="datatable" class="table table-hover">
            <thead>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Dependencia</th>
              <th>Operación</th>
            </thead>
            <tbody>
              {% for e in object_list %}
              <tr>
                <td>{{e.nombre}}</td>
                <td>{{e.apellido}}</td>
                <td>{{e.area}}</td>
                <td>
                  <a href="{% url 'editarEmpleados' e.id %}" class="btn btn-primary">Modificar</a>
                  <a href="{% url 'editarEmpleados' e.id %}" class="btn btn-danger eliminar-empleado" data-empleado-id="{{ e.id }}">Eliminar</a>

                  <!-- <a href="{% url 'editarEmpleados' e.id %}" class="btn btn-danger" onclick="DeleteSweet('{{ empleado.id }}')" data-method="delete" data-confirm="¿Estás seguro de eliminar este empleado?">Eliminar</a> -->
                </td>
              </tr>
            {% endfor %}
            </tbody>           

          {% if is_paginated %}

            <div class="mt-2">
              <ul class="pagination">

                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a href="#" class="page-link">Previous</a>
                  </li>
                {% endif %}
                  
                {% for i in paginator.page_range %}
                  <li class="page-item  {% if page_obj.number == i %} active {% endif %}">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                  </li>
                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                  </li>
                {% else %}
                <li class="page-item disabled">
                  <a href="#" class="page-link">Next</a>
                </li>
                {% endif %}

                </ul>
            </div>

          {% endif %}

        </table>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
</body>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'js/sweetAlert/EliminarEmpleadoSweetAlert.js' %}"></script>
</html>

templates/salidaVisitantes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> {{ titulo }} </title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">	
</head>
<body style="overflow-x: hidden;">
	<img id="apostar" src="{% static 'img/apostar1.jpg' %}" style="width: 100%;">
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#" style="padding: 4px;">
        <img alt="Brand" src="{% static 'img/apostar.jpg' %}" style="width: 40px; height: 40px;">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'index' %}">menú</a></li>
        <li><a href="{% url 'login' %}">Salir</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	
<div class="">
  <div class="page-title">
  <div class="title_left">
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
    <div class="x_title">
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <br />
      <div class="col-md-10 col-md-offset-1">
        <div class="col-md-4">
        </div>
        <table id="tablaVisitas" class="table table-hover">
          <thead>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Identificación</th>
            <th>Empresa</th>
            <th>Area de visita</th>
            <th>Empleado</th>
            <th>Elemento</th>
            <th>Marca</th>
            <th>Serial</th>
            <th>Fecha Ingreso</th>
            <th>Salida</th>
            </thead>
          <tbody>
            {% for v in object_list %}
              {% if not v.salida_set.all %}
                <tr>
                  <!-- Otros campos de la tabla -->
                  <td>{{v.nombres}}</td>
                  <td>{{v.apellidos}}</td>
                  <td>{{v.identificacion}}</td>
                  <td>{{v.empresa}}</td>
                  <td>{{v.area_id}}</td>
                  <td>{{v.empleado_id}}</td>
                  <td><b>{{v.tipo_equipo}}</b></td>
                  <td><b>{{v.marca}}</b></td>
                  <td><b>{{v.serial}}</b></td>
                  <td>{{v.created_at}}</td>
                  <td>
                    <form method="POST" action="{% url 'salida_visitante' v.id %}" accept-charset="UTF-8" class="salida-form" id="salidarecepcion-{{ v.id }}">
                      {% csrf_token %}
                      <input class="btn btn-danger" type="submit" value="Salida">
                    </form>
                  </td>            
                </tr>		
              {% endif %}			
            {% endfor %}
          </tbody>			
        </table>
      </div>
    </div>
    </div>
  </div>
  </div>  
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'js/sweetAlert/DarSalidaSweetAlert.js' %}"></script>
</body>
</html>